/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zjy_js_customdialog_JniTest */

#ifndef _Included_com_zjy_js_customdialog_JniTest
#define _Included_com_zjy_js_customdialog_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zjy_js_customdialog_JniTest
 * Method:    getString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zjy_js_customdialog_JniTest_getString
  (JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jintArray JNICALL
Java_com_zjy_js_customdialog_opencvutils_ImageUtils_getModifyOrientation(JNIEnv *env, jclass type, jintArray pixs_, jint width,
 jint height);
#ifdef __cplusplus
}
#endif
#endif