/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstring>
/* Header for class com_zjy_js_customdialog_JniTest */
#include "com_zjy_js_customdialog_JniTest.h"


#ifdef __cplusplus

extern "C" {
#endif
/*
 * Class:     com_zjy_js_customdialog_JniTest
 * Method:    getString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zjy_js_customdialog_JniTest_getString
        (JNIEnv *env, jobject obj1, jstring str1, jstring str2) {
    const char *str = env->GetStringUTFChars(str1,0);
    const char *str3 =env->GetStringUTFChars(str2,0);
    const char *strText="says to";
    const size_t len = strlen(str)+strlen(strText)+strlen(str3);
    char *n_str = new char[len+1];
    strcpy(n_str,str);
    strcat(n_str,strText);
    strcat(n_str,str3);
    jstring result=env->NewStringUTF(n_str);
    env->ReleaseStringUTFChars(str1,str);
    env->ReleaseStringUTFChars(str2,str3);
    delete [] n_str;
    //
//    stringstream ss;
//    const char *p1 = env->GetStringUTFChars(str1, 0);
//    const char *p2 = env->GetStringUTFChars(str2, 0);
//    ss << p1 << " says woshishazi to " << p2 << endl;
//    env->ReleaseStringUTFChars(str1, p1);
//    env->ReleaseStringUTFChars(str2, p2);
//    jstring result=env->NewStringUTF(ss.str().c_str());
    return result;
}


//JNIEXPORT jintArray JNICALL Java_com_zjy_js_customdialog_JniTest_getGrayArray(JNIEnv *env,jclass obj,jintArray buf,int w,int h)
//{
//    jint *cbuf;
//    cbuf = env->GetIntArrayElements(buf,JNI_FALSE);
//    if (NULL == cbuf)
//    {
//        return 0;
//    }
//
//   Mat imgData(h,w,CV_8UC4,(unsigned char*) cbuf);
//
//    u_char *ptr = imgData.ptr(0);
//    for (int i = 0; i < w*h; ++i)
//    {
//        //图像存储方式为：BGRA
//        int grayScale = (int)(ptr[4*i+2]*0.299 + ptr[4*i+1]*0.587 + ptr[4*i+0]*0.144 );
//        ptr[4*i+0] = grayScale;
//        ptr[4*i+1] = grayScale;
//        ptr[4*i+2] = grayScale;
//    }
//
//    int size = w * h;
//    jintArray  result = env->NewIntArray(size);
//    env->SetIntArrayRegion(result,0,size,cbuf);
//    env->ReleaseIntArrayElements(buf,cbuf,0);
//    return result;
//}

#ifdef __cplusplus
}
#endif
